### ISSUE TITLE
Activity: Profile page should only show Open Activities

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#11]
The title should read "My Current Activities" and it should not include Activities that are Canceled or Completed.

**Comment by adityadigitalomnibus** [comment]
Fixed

**Comment by douglaswyatt** [comment]
It does not appear to be fixed.

**Comment by douglaswyatt** [comment]
Still not working: 
![screen shot 2017-01-23 at 11 02 57 am](https://cloud.githubusercontent.com/assets/23498712/22193413/155c9cbc-e161-11e6-84be-1cf2ada2ee52.png)

**Comment by douglaswyatt** [comment]
I am still seeing this occasionally.  I flip between various browsers and have seen it on all of them.  And sometimes it goes away and then comes back in the same session.  I'm _pretty_ sure this isn't because of not clearing  my browser cache since I have done it occasionally (and with Firefox, I clean the cache every time I quit the browser).  So I think there's still something going on here.

**Comment by douglaswyatt** [comment]
Get rid of the search/filter bar on the Profile page. and hard-code to only and always show all Cases or Activities owned by the logged in user and not in a closed stage.

**Comment by douglaswyatt** [comment]
Appears to be fixed.
