### ISSUE TITLE
General: if my window isn't quite wide, the logged-in username in the upper right does not appear.

### ISSUE THREAD

**Issue by douglaswyatt** [adityadigitalomnibus/goliath#21]
If I click where it should be, I get the Report-a-bug and logout menu. If I widen it, it shows up.  If I shrink it, it disappears again.

**Comment by douglaswyatt** [comment]
![screen shot 2016-12-27 at 11 53 44 am](https://cloud.githubusercontent.com/assets/23498712/21494873/644ab21e-cc3a-11e6-95e1-4bd6d1269198.png)

**Comment by douglaswyatt** [comment]
![screen shot 2016-12-27 at 11 55 44 am](https://cloud.githubusercontent.com/assets/23498712/21494881/70600310-cc3a-11e6-9d70-3a17acca1229.png)

**Comment by adityadigitalomnibus** [comment]
Now it will show an arrow to open and close that right side menu on smaller screen. Its fixed now.

**Comment by douglaswyatt** [comment]
It requires it to be bizarrely wide for it to display the name.  There's loads of available space for the name, so I'm not sure why it needs even more.  Can you adjust the width required to show it?  I never have browser "maximized" and have to widen it wider than I usually keep it to see it.

**Comment by douglaswyatt** [comment]
Seems better now, but still not sure why it has to disappear when there's lots of space on the top row.  But maybe revisit it later.
